### ISSUE TITLE
CLC workflow for CDC NCIRD/DVD ONT & Illumina NEBNext Sequencing Protocol

### ISSUE THREAD

**Issue by jonathanjacobs** [CDCgov/SARS-CoV-2_Sequencing#11]
@dmaccannell - i pulled together CLC workflows for both the CDC's Nanopore and CDC Illumina/NEBNext protocols that are in the CDC/DVID manual. These should be self contained, and run out of the box on CLCv20.

If anyone at CDC, PHL or elsewhere is using Clint's protocols and also uses CLC  - perhaps these will be useful.

[CDC Nanopore Amplicon SARSCOV2 Protocol CLC Worklow v0.1.zip](https://github.com/CDCgov/SARS-CoV-2_Sequencing/files/4412932/CDC.Nanopore.Amplicon.SARSCOV2.Protocol.CLC.Worklow.v0.1.zip)

[CDC Illumina NEBNext SARSCOV2 CLC Workflow v0.2.zip](https://github.com/CDCgov/SARS-CoV-2_Sequencing/files/4412933/CDC.Illumina.NEBNext.SARSCOV2.CLC.Workflow.v0.2.zip)

Any feedback is welcome. Readme/pdfs inside the zips have additional details.

**Comment by dmaccannell** [comment]
I'll merge it in.
