### ISSUE TITLE
Updated ONT protocol

### ISSUE THREAD

**Issue by embatty** [CDCgov/SARS-CoV-2_Sequencing#12]
There is an update to the ONT PCR tiling protocol: https://community.nanoporetech.com/posts/covid-19-protocol-update
It's now on rev E. I can add a pull request if you like, do you want to keep the previous versions archived somewhere or just replace with the latest? The full protocol filename has the revision letter in it but not the checklist version.

**Comment by dmaccannell** [comment]
Either would be fine. If you want to submit a pull request, that's fine. That URL is behind a login, though.
