### ISSUE TITLE
Updated CLC Workflows for CDC protocols

### ISSUE THREAD

**Issue by jonathanjacobs** [CDCgov/SARS-CoV-2_Sequencing#13]
I'm updated both the Nanopore and Illumina/NEBNext workflows in CLC for the CDC NGS procotols. ZIP files attached. Can these be added to the repo to replace the current ones? The change log is in the README for each zip archive, and I've added updates below as well. 

**SARSCOV2 Variant Calling Pipeline for Illumina NEBNext CDC Protocol v0.3**
[CDC Illumina NEBNext SARSCOV2 CLC Workflow v0.3.zip](https://github.com/CDCgov/SARS-CoV-2_Sequencing/files/4422162/CDC.Illumina.NEBNext.SARSCOV2.CLC.Workflow.v0.3.zip)
CHANGE LOG
0.3
- Updated QC&trimming to q20 (0.01) and maximum 2 ambigous reads.
- Updated variant calling settings. Specifically,
-- coverage and count filter settings to a Minimum coverage 100, Minimum count 10, and Minimum frequency 1%.
-- base quality filter settings with a Neighborhood radius 5, Minimum central quality q30, Minimum neighborhood quality	q20.
-- read direction filter settings to include Direction frequency filter 5% and Relative read direction filter 1% significance.
-- remove homopolymer variant error filter is active for regions with minimum length 3 and a  frequency below 80% will be filtered.

**SARSCOV2 Pipeline for CDC Nanopore Protocol**
[CDC Nanopore Amplicon SARSCOV2 CLC Worklow v0.2.zip](https://github.com/CDCgov/SARS-CoV-2_Sequencing/files/4422164/CDC.Nanopore.Amplicon.SARSCOV2.CLC.Worklow.v0.2.zip)
CHANGE LOG
0.2
- Updated trim and QC step to remove homopolymer stretches on the 3' end of reads. This setting is conservatively set to 9 bp or more, so it is enabled as a precaution only.
- Updated to include adapter trimming specifically for ONT 1D Ligation adapter kit, which is specified by CDC protocol. 
- Updated variant calling settings. Specifically, 
-- removed base quality filter, since error correction step of RACON does not output quality scores
-- updated coverage and count filter settings to a Minimum coverage 100, Minimum count 20,and Minimum frequency 20%.
-- remove homopolymer variant error filter is active for regions with minimum length 3 and a  frequency below 80% will be filtered.

**Comment by jonathanjacobs** [comment]
Added updated version of CLC workflow for ARTICv3 Nanopore Protocol - details inside the readme, but but basically aligned parameters with CDC nanopore workflow for CLC for variant calling etc. Also updated the amplicon filtering to match what is done for ARTICv3 (400/700bp filter, etc.)

If you're using ARTICv1 or v2 primer sets - you can simply replace the bed file used in the workflow using CLC's Import Primer Pairs tool. 

Feedback is welcome. Let me know if anyone has questions. 

[ARTICv3 Nanopore SARSCOV2 CLC Workflow v0.2.zip](https://github.com/CDCgov/SARS-CoV-2_Sequencing/files/4423165/ARTICv3.Nanopore.SARSCOV2.CLC.Workflow.v0.2.zip)

**Comment by dmaccannell** [comment]
Added.
