### ISSUE TITLE
include direct RNA nanopore sequencing resource?

### ISSUE THREAD

**Issue by enovoa** [CDCgov/SARS-CoV-2_Sequencing#15]
Hello, we have built a resource of direct RNA nanopore sequencing datasets that are publicly available and are processing them in uniform manner and placing the processed data in the resource.
Can you include our resource in your list of availalable sequencing resources?
https://biocorecrg.github.io/covid/

Thanks so much!
Eva

**Comment by dmaccannell** [comment]
Added. Sorry for the delay. Busy week.
