### ISSUE TITLE
CLC plugin

### ISSUE THREAD

**Issue by p-dekker** [CDCgov/SARS-CoV-2_Sequencing#16]
I build a plugin CLC Genomics Workbench to extend to functionality if the workbench. I wrote the plugin some time ago for analysis of Influenza Virus Illumina data. I updated it so it nicely works on SARS-CoV-2 data. The tools in the plugin will also add the annotation to genome and does report the detected variants compared to the reference and the is reference based approach but it spend more time extracting the consensus and will use the novo assembly if the consensus is to far of the reference. 

It did test it on some Illumina SARS-CoV-2 data I found on SRA archive. The original Influenze tool is still in active use and is validated on the lab.

I'm willing to donate the plugin the covid community.. if there is any interest. (you need a CLC genomics workbench license to run the tool!)

**Comment by dmaccannell** [comment]
Sure. We have some official CLCbio/QIAGEN tools as well, but I'd be happy to add it.
