### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [CDCgov/SARS-CoV-2_Sequencing#20]
This repo is missing a LICENSE file.  [The README.md file includes a license](https://github.com/CDCgov/SARS-CoV-2_Sequencing#license), but a license file makes it easier to tell what the license is at a glance.

**Comment by dmaccannell** [comment]
Licensing is indicated in README.md, and is hyperlinked inline. Insufficient?

**Comment by TechnologyClassroom** [comment]
The license blurb says, "You should have received a copy of the Apache Software License along with this program."  This patch would do that in addition to indicating the license unobtrusively at the top of the page instead of 98% of the way down the page.
