### ISSUE TITLE
IDseq to the list of resources. 

### ISSUE THREAD

**Issue by efahsbender1** [CDCgov/SARS-CoV-2_Sequencing#30]
We would love to add IDseq to the list of resources!
https://idseq.net

automated pipeline for building SARS-CoV-2 consensus genomes.
pipeline: https://github.com/chanzuckerberg/idseq-workflows/blob/main/consensus-genome/run.wdl

**Comment by dmaccannell** [comment]
Added as #18 under bioinformatic tools and methods. Thanks, Liz!

**Comment by efahsbender1** [comment]
Thank you!!
