### ISSUE TITLE
Update QIAGEN / CLC verbiage

### ISSUE THREAD

**Issue by jonathanjacobs** [CDCgov/SARS-CoV-2_Sequencing#4]
@dmaccannell / thanks for setting this up. 

Please change the section for CLC to the following::

QIAGEN Digital Insights has created example workflows and tutorials for Illumina and Oxford Nanopore data using CLC Genomics Workbench v20.0.3. Note - these workflows are "For Research Use Only", and may need to modified to fit a particular labs' upstream protocols. Please tailor these to fit your specific needs. If you have any questions - contact Jonathan Jacobs (jonathan.jacobs@qiagen.com) and Leif Schauser (leif.schauser@qiagen.com) and we'll set up a meeting to discuss.

QDI will also be hosting a series of webinars and providing free temporary licenses for CLC Genomics Workbench and Ingenuity Pathway Analysis software to all labs involved in the analysis of SARSCOV2. Details can be found here. [https://go.qiagen.com/QDI-COVID19](https://go.qiagen.com/QDI-COVID19)

- [SARSCoV2 Analysis Tutorial with Nanopore Data](https://resources.qiagenbioinformatics.com/tutorials/Analysis_of_SARS-CoV-2.pdf)

- [SARSCOV2 Workflow and Tutorial Data for Nanopore Data](http://resources.qiagenbioinformatics.com/testdata/SARS-CoV-2_MinION_example_data.zip) | [PNG of Workflow Design](https://user-images.githubusercontent.com/64888/77170622-ad637500-6a91-11ea-9b2a-f6f3cda4981e.png)
- [Example workflow for Illumina Data](https://github.com/CDCgov/SARS-CoV-2_Sequencing/files/4359655/SARSCOV2.Illumina.Vanilla-0.1.cpw.zip) | [PNG of Workflow Design](https://user-images.githubusercontent.com/64888/77166238-4098ac80-6a8a-11ea-9b38-534fe956258b.png)

**Comment by dmaccannell** [comment]
Added. Thanks.
