### ISSUE TITLE
Broken link in document (NCBI-Sequence_submission_for_COVID-19.pdf)

### ISSUE THREAD

**Issue by marcoxa** [CDCgov/SARS-CoV-2_Sequencing#8]
Hi

the link

https://github.com/CDCgov/SARS-CoV-2_Sequencing/blob/master/NCBI-Submission/NCBI-Sequence_submission_for_COVID-19.pdf

is broken (404).

Just letting you know.

Marco Antoniotti

**Comment by marcoxa** [comment]
For completeness, it is under the heading "1. NCBI Submission Portal"

**Comment by dmaccannell** [comment]
Good catch. Fixed. PDF was in the repository, I just bungled the link.
