### ISSUE TITLE
Regarding oxford nanopore data analysis

### ISSUE THREAD

**Issue by ps120195** [CDCgov/SARS-CoV-2_Sequencing#9]

**Comment by dmaccannell** [comment]
Was there a specific issue, or is this more of a philosophical conjecture?

**Comment by ps120195** [comment]
Hii,

Please find the attachments. I ran SARS-Cov2 sequencing pipeline for
nanopore data, where I am getting two kinds of results.
All the commands were same ,even the samples were same,but ran on different
systems.

Can you tell why this is happening?

**Comment by dmaccannell** [comment]
Happy to help. Which pipeline? Attachments were missing.

**Comment by ps120195** [comment]
![image1](https://user-images.githubusercontent.com/62909237/77960682-60379c80-72f6-11ea-9509-427466cea242.jpeg)
![image2](https://user-images.githubusercontent.com/62909237/77960710-688fd780-72f6-11ea-96ee-deb6470bf3a5.jpeg)

**Comment by ps120195** [comment]
I ran it thrice, still I am not getting details of vcf which is there in the image 1 ,saying the fasta sequence does not match the REF allele ... and so on

**Comment by dmaccannell** [comment]
If these are two different systems, you're sure that the perl environment and all dependencies are the same version?

**Comment by ps120195** [comment]
Does that make any difference like this?

**Comment by ps120195** [comment]
All dependencies and perl environment is same for sure

**Comment by ps120195** [comment]
Also the dependencies were installed by pip ,so versions of dependencies
are same in both systems. Please suggest why this is happening .what is the
actual output we expect from this vcf_mask_lowcoverage.pl in terminal.

**Comment by donutbrew** [comment]
I'm not clear on the difference between screen shots 1 and 2. 

In screenshot 1, it looks like it finished correctly. Did you get a reasonable consensus in 'consensus.fasta'?

In screenshot 2, something went wrong. Are you using the same reference fasta that was used for read mapping? Bcftools is very picky about the vcf and the reference to which it applies variants. It may be possible that the reference was getting masked incorrectly, but I can't work out why that would be. I wonder if you could check the `samtools depth` at position 8782 and potentially let me have a look at your vcf? Interestingly, position 8782 is one where we have observed a lot of variation.

**Comment by ps120195** [comment]
Yes I am using the same reference that i used for mapping.

**Comment by ps120195** [comment]
![consensus_and_reference](https://user-images.githubusercontent.com/62909237/78050139-7fd3d100-7399-11ea-8b59-a3882d5a4a17.jpeg)
consensus2.fasta is my consensus fasta and MN908947.3.fasta is my reference file which i used in mapping too.Also I am getting that C to T variant at same 8782 location 
![vcf_location](https://user-images.githubusercontent.com/62909237/78050574-0f797f80-739a-11ea-930e-d0ae5f58cbfd.jpeg)

**Comment by ps120195** [comment]
samtools depth at position 8782 is 1871

**Comment by ps120195** [comment]
Here I ran from start till last,still result is same, please see the screenshot
![full_pipeline](https://user-images.githubusercontent.com/62909237/78052650-0a69ff80-739d-11ea-969c-146b04dec7fa.jpeg)

**Comment by donutbrew** [comment]
Hmm. I'd like to get to the bottom this, but I need a little more info. Can you show me the output of the following:
 
`bcftools view VIC07_ONT.vcf |grep -EC3 "\s8282\s"`
`bcftools view VIC07_ONT.vcf.masked.vcf.gz |grep -EC3 "\s8282\s"`

**Comment by ps120195** [comment]
![bcftools view](https://user-images.githubusercontent.com/62909237/78057636-b236fb80-73a4-11ea-947b-cf2621e9c866.jpeg)

**Comment by ps120195** [comment]
![bcftools_view_EC](https://user-images.githubusercontent.com/62909237/78057944-30939d80-73a5-11ea-8914-435e25861b73.jpeg)
It was -EC3 ,,sorry

**Comment by donutbrew** [comment]
Those look OK to me. The only other thing I can think of is that there is something funky going on with the reference. Can you try running `dos2unix MN908947.3.fasta` and then running the script again? If that is the issue, I can make a change to fix this (I will add it in in any case).

**Comment by ps120195** [comment]
Yaa sure ,

**Comment by ps120195** [comment]
I tried dos2Unix command and ran the full script again, Still no change in output.
![Cap1](https://user-images.githubusercontent.com/62909237/78064053-c54ec900-73ae-11ea-83b4-3fa0cd9a160b.PNG)
![Cap2](https://user-images.githubusercontent.com/62909237/78064060-c7188c80-73ae-11ea-9777-c65d46d33d01.PNG)

**Comment by ps120195** [comment]
I tried now using  MN908947.fna instead of MN908947.fasta ,and it worked.
See the output
![cap3](https://user-images.githubusercontent.com/62909237/78066976-8bcc8c80-73b3-11ea-9f17-6fd5ba3e7da1.PNG)

**Comment by donutbrew** [comment]
Ok, so it looks like you converted the line endings for "MN908947.fasta" and it worked. Using "MN908947.fna" (which is identical except line endings were not converted to unix line endings) trows the error. I think these are all consistent, unless I misunderstand you. I will make the change to take into consideration fasta files with Windows line endings.

**Comment by ps120195** [comment]
Thank you for helping me out. I learnt alot during this error hunt.As the error is resolved ,I want to know if I have to use only file.fna  for this pipeline ?

**Comment by donutbrew** [comment]
No worries! Glad you caught this, as it's an easy fix but annoying for users. 
The filename doesn't matter. As long as the fasta header is the same and (for now) the windows line endings of your reference file are converted to unix line endings.
